controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\TodoController::todos
delete_todo:
    path: /api/todos/{id}
    controller: App\Controller\TodoController::deleteTodo
    methods: [DELETE, POST]
get_todo:
    path: /api/todos/{id}
    controller: App\Controller\TodoController::getTodo
    methods: GET
add_todo:
    path: /add_todo
    controller: App\Controller\TodoController::addTodo
    methods: POST
api_todo_list:
    path: /api/todos
    controller: App\Controller\TodoController::getTodos
    methods: GET
update_todo:
    path: /api/todos/{id}
    controller: App\Controller\TodoController::updateTodo
    methods: PUT
get_subtodo:
    path: /api/subtodo/{id}
    controller: App\Controller\SubToDoController::getSubToDo
    methods: GET
get_subtodos:
    path: /api/subtodos/{parentTodoId}
    controller: App\Controller\SubToDoController::getSubToDos
    methods: GET
add_subtodo:
    path: /add_subtodo
    controller: App\Controller\SubToDoController::addSubToDo
    methods: POST
update_subtodo:
    path: /api/subtodos/update/{id}
    controller: App\Controller\SubToDoController::updateSubTodo
    methods: PUT
delete_subtodo:
    path: /api/subtodos/{id}
    controller: App\Controller\SubToDoController::deleteSubTodo
    methods: [DELETE, POST]